Proprietor/Models/Accounting.cs
namespace Proprietor.Models
{
    public class Accounting
    {
        public int Id { get; set; }
        public virtual GameAccount GameAccount { get; set; }

        public decimal Value { get; set; }
    }
}

Proprietor/Models/Buildings.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Proprietor.Models
{
    public class Buildings
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Street { get; set; }
        public virtual City City { get; set; }

        public decimal Value { get; set; }
        public decimal Income { get; set; }
        public decimal Expense { get; set; }

        public virtual List<GameAccount> GameAccounts { get; set; }

    }
}

Proprietor/Models/City.cs
using System.Collections.Generic;

namespace Proprietor.Models
{
    public class City
    {
        public int Id { get; set; }

        public string CityName { get; set; }
        public virtual Country Country { get; set; }
        public virtual List<GameAccount> GameAccounts { get; set; }

    }
}

Proprietor/Models/Country.cs
using System.Collections.Generic;

namespace Proprietor.Models
{
    public class Country
    {
        public int Id { get; set; }
        public int CountryName { get; set; }
        public virtual List<City> Cities { get; set; }

    }
}

Proprietor/Models/Entity.cs
namespace Proprietor.Models
{
    using System.Data.Entity;

    public class Entity : DbContext
    {
        public Entity()
            : base("name=Entity")
        {
        }

        public DbSet<UserAccount> UserAccount { get; set; }
        public DbSet<Accounting> Accountings { get; set; }
        public DbSet<GameAccount> GameAccounts { get; set; }
        public DbSet<City> Cities { get; set; }
        public DbSet<Buildings> Buildings { get; set; }
        public DbSet<Country> Countries { get; set; }
    }
}

Proprietor/Models/GameAccount.cs
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace Proprietor.Models
{
    public class GameAccount
    {
        public int Id { get; set; }
        //public virtual UserAccount UserAccount { get; set; }

        public virtual List<Accounting> Accountings { get; set; }
        public string CurrentLocation { get; set; }

    }
}

Proprietor/Models/UserAccount.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.ComponentModel.DataAnnotations;

namespace Proprietor.Models
{
    public class UserAccount
    {
        [Key]
        public int UserId { get; set; }

        [Required(ErrorMessage = "First name is requrid.")]
        public string FirstName { get; set; }

        [Required(ErrorMessage = "Last name is requrid.")]
        public string LastName { get; set; }

        [Required(ErrorMessage = "Email is requrid.")]
        //TODO: VALIDATE EMAIL HERE
        public string Email { get; set; }
        
        [Required(ErrorMessage = "Username is requrid.")]
        public string UserName { get; set; }

        [Required(ErrorMessage = "Password is requrid.")]
        [DataType(DataType.Password)]
        public string Password { get; set; }

        [Compare("Password", ErrorMessage = "Please confirm your password")]
        [DataType(DataType.Password)]
        public string ConfirmPassword { get; set; }

        public virtual GameAccount GameAccount { get; set; }

    }
}

Proprietor/Controllers/AccountController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Proprietor.Models;

namespace Proprietor.Controllers
{
    public class AccountController : Controller
    {
        // GET: Account
        public ActionResult Index()
        {
            using (Entity db = new Entity())
            {
                return View(db.UserAccount.ToList());
            }
        }

        public ActionResult Register()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Register(UserAccount account)
        {
            if (ModelState.IsValid)
            {
                using (Entity db = new Entity())
                {
                    db.UserAccount.Add(account);
                    db.SaveChanges();
                }
                ModelState.Clear();
                ViewBag.Message = account.FirstName + " " + account.LastName + " succesfully registered.";
            }
            return View();
        }

        //Login
        public ActionResult Login()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Login(UserAccount user)
        {
            using (Entity db = new Entity())
            {
                var usr = db.UserAccount.Single(u => u.Email == user.Email && u.Password == user.Password);
                if (usr != null)
                {
                    Session["UserId"] = usr.UserId.ToString();
                    Session["Username"] = usr.UserName.ToString();
                    return RedirectToAction("LoggedIn");
                }else
                {
                    ModelState.AddModelError("", "Username or Password is wrong.");
                }
            }
            return View();
        }

        public ActionResult LoggedIn()
        {
            if (Session["UserId"] != null)
            {
                return View();
            }
            else
            {
                return RedirectToAction("Login");
            }
        }
        public ActionResult LogOut()
        {
            Session.Abandon();

            return RedirectToAction("Index", "Home");
        }
    }
}

Proprietor/Controllers/ForumController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Proprietor.Controllers
{
    public class ForumController : Controller
    {
        // GET: Forum
        public ActionResult Index()
        {
            return View();
        }
    }
}

Proprietor/Controllers/GameController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Routing;

namespace Proprietor.Controllers
{
    

    public class GameController : Controller
    {
        // GET: Game
        public ActionResult Index()
        {
            if(Session["UserId"] != null)
            {

                return View();
            }
            return RedirectToAction("Index", "Home");
        }
    }

    //dude
}

Proprietor/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Proprietor.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

Proprietor/Views/Game/Index.cshtml
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_LayoutGame.cshtml";
}

Proprietor/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

Proprietor/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

Proprietor/Views/Home/Index.cshtml
<section id="hero" class="row" style="height:100vh;background-image:url(/media/slider/slider1.jpg)">


</section>

Proprietor/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    <style>
        li.dropdown {
            display: inline-block;
        }

        .dropdown-content {
            display: none;
            position: absolute;
            background-color: #f9f9f9;
            min-width: 160px;
            box-shadow: 0px 8px 16px 0px rgba(0,0,0,0.2);
            z-index: 1;
        }

            .dropdown-content a {
                color: black;
                padding: 12px 16px;
                text-decoration: none;
                display: block;
                text-align: left;
            }

                .dropdown-content a:hover {
                    background-color: #f1f1f1;
                }

        .dropdown:hover .dropdown-content {
            display: block;
        }
    </style>
</head>

<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Proprietor", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse navbar-right">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Play the game", "Index", "Game")</li>
                    <li>@Html.ActionLink("Forum", "Index", "Forum")</li>
                    @if (Session["UserId"] != null)
                    {
                        <li class="dropdown">
                            <a href="/Account/LoggedIn">Hello @Session["Username"].ToString()</a>
                            <div class="dropdown-content">
                                <a href="#">1</a>
                                <a href="#">1</a>
                                @Html.ActionLink("Log out", "LogOut", "Account")
                            </div>
                        </li>
                    }
                    else
                    {
                        <li>@Html.ActionLink("Login", "Login", "Account")</li>
                    }

                </ul>
            </div>
        </div>
    </div>
    <div class="container-fluid body-content">
        @RenderBody()

    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

Proprietor/Views/Shared/_LayoutGame.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    <style>
        li.dropdown {
            display: inline-block;
        }

        .dropdown-content {
            display: none;
            position: absolute;
            background-color: #f9f9f9;
            min-width: 160px;
            box-shadow: 0px 8px 16px 0px rgba(0,0,0,0.2);
            z-index: 1;
        }

            .dropdown-content a {
                color: black;
                padding: 12px 16px;
                text-decoration: none;
                display: block;
                text-align: left;
            }

                .dropdown-content a:hover {
                    background-color: #f1f1f1;
                }

        .dropdown:hover .dropdown-content {
            display: block;
        }
    </style>
</head>

<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Proprietor", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse navbar-right">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Play the game", "Index", "Game")</li>
                    <li>@Html.ActionLink("Forum", "Index", "Forum")</li>
                    @if (Session["UserId"] != null)
                    {
                        <li class="dropdown">
                            <a href="/Account/LoggedIn">Hello @Session["Username"].ToString()</a>
                            <div class="dropdown-content">
                                <a href="#">1</a>
                                <a href="#">1</a>
                                @Html.ActionLink("Log out", "LogOut", "Account")
                            </div>
                        </li>
                    }
                    else
                    {
                        <li>@Html.ActionLink("Login", "Login", "Account")</li>
                    }

                </ul>
            </div>
        </div>
    </div>
    <div class="container-fluid body-content">
        @RenderBody()

    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>